apiVersion: v1
kind: Pod
metadata: 
  name: sidecar-pod
spec: 
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared
      mountPath: /usr/share/nginx/html
  - name: apache
    image: httpd
    command: ["/bin/sh", "-c"]
    args:
      - while true; do echo "Hello from Apache" >> /data/index.html; sleep 5; done
    volumeMounts:
    - name: shared
      mountPath: /data
  volumes:
  - name: shared
    emptyDir: {}
