apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
data:
  APP_MODE: production
  APP_COLOR: blue 
---
apiVersion: v1
kind: Secret
metadata:
  name: shared-secret
type: Opaque
stringData:
  DB_USER: "admin"
  DB_PASS: "123456"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shared-app
  template:
    metadata:
      labels:
        app: shared-app
    spec:
      containers:
      - name: app
        image: nginx
        envFrom:
        - configMapRef:
            name: shared-config
        - secretRef:
            name: shared-secret
        ports:
        - containerPort: 80



